city_to_code = {
    "Seattle": "SEA",     
    "London": "LON",     
    "Paris": "PAR",       
    "Brussels": "BRU",    
    "Amsterdam": "AMS",   
    "Milan": "MIL",       
    "Venice": "VCE",      
    "Florence": "FLR",    
    "Rome": "ROM",        
    "Athens": "ATH",      
    "Santorini": "JTR",  
    "Berlin": "BER",      
    "Prague": "PRG",      
    "Budapest": "BUD",   
    "Vienna": "VIE",      
    "Zurich": "ZRH",      
    "Barcelona": "BCN",   
    "Seville": "SVQ",     
    "Lisbon": "LIS",      
}
