city_to_iata = {
    "Seattle": "SEA",
    "London": "LHR",
    "Paris": "CDG",
    "Brussels": "BRU",
    "Amsterdam": "AMS",
    "Milan": "MXP",
    "Venice": "VCE",
    "Florence": "FLR",
    "Rome": "FCO",
    "Athens": "ATH",
    "Santorini": "JTR",
    "Berlin": "BER",
    "Prague": "PRG",
    "Budapest": "BUD",
    "Vienna": "VIE",
    "Zurich": "ZRH",
    "Madrid": "MAD",
    "Barcelona": "BCN",
    "Seville": "SVQ",
    "Lisbon": "LIS",
}